schema-version = 1

[package]
title = "HamClock for Amazon Vega OS"
version = "4.33.0"
id = "org.openhamclock.hamclock"

[os.version]
min = "1.2"
target = "1.2"

[needs]
[[needs.module]]
id = "/com.amazon.vega.os@IVega_1_2"

[[needs.module]]
id = "/com.amazon.kepler.keplerscript_4@IKeplerScript_0"

[[needs.module]]
id = "/com.amazon.kepler.webview_4@IWebview_4"



[components]
[[components.interactive]]
id = "org.openhamclock.hamclock.main"
runtime-module = "/com.amazon.kepler.runtime.react_native_kepler_4@IReactNativeKepler_0"
launch-type = "singleton"
categories = ["com.amazon.category.main"]

[wants]
[[wants.service]]
id = "com.amazon.webview.renderer_service"

[[wants.service]]
id = "com.amazon.inputmethod.service"

[[wants.service]]
id = "com.amazon.audio.stream"

[[wants.service]]
id = "com.amazon.audio.control"

[[wants.service]]
id = "com.amazon.gipc.uuid.*"

[offers]
[[offers.service]]
id = "com.amazon.gipc.uuid.*"
