// Auto-generated by gen_antenna_data.sh -- do not edit by hand
// Source:    /home/dave/mygit/hamclock_komacke/integration/build/voacap.ant.csv
// Generated: 2026-04-28 00:04:20 UTC
//
// Copyright(c) 2026 HamClock Contributors and David Strickland KR8X
// Licensed under the MIT License.
// See LICENSE file in the project root for full license information

#ifndef ANTENNA_DATA_H
#define ANTENNA_DATA_H

#include <cstdint>

struct AntennaEntry {
	uint16_t    index;          // msb*256 + lsb
	const char *path;
	const char *description;
};

// clang-format off
static const AntennaEntry ANTENNA_DATA[] = {
	//  index    path                                    description
    {     0,  "default/isotrope",                  "ISOTROPE" },
    {   256,  "default/ccir.000",                  "ISOTROPE" },
    {   257,  "default/ccir.001",                  "HR 4/4/1" },
    {   258,  "default/ccir.002",                  "HR 4/4/.8" },
    {   259,  "default/ccir.003",                  "HR 4/4/.5" },
    {   260,  "default/ccir.004",                  "HR 4/3/.5" },
    {   261,  "default/ccir.005",                  "HR 4/2/.5" },
    {   262,  "default/ccir.006",                  "HR 4/2/.3" },
    {   263,  "default/ccir.007",                  "HR 2/4/1" },
    {   264,  "default/ccir.008",                  "HR 2/4/.8" },
    {   265,  "default/ccir.009",                  "HR 2/4/.5" },
    {   266,  "default/ccir.010",                  "HR 2/3/.5" },
    {   267,  "default/ccir.011",                  "HR 2/2/.5" },
    {   268,  "default/ccir.012",                  "HR 2/2/.3" },
    {   269,  "default/ccir.013",                  "HR 2/1/.5" },
    {   270,  "default/ccir.014",                  "HR 2/1/.3" },
    {   271,  "default/ccir.015",                  "HR 1/2/.5" },
    {   272,  "default/ccir.016",                  "HR 1/2/.3" },
    {   273,  "default/ccir.017",                  "HR 1/1/.5" },
    {   274,  "default/ccir.018",                  "HR 1/1/.3" },
    {   275,  "default/ccir.019",                  "TR 2/1/.5" },
    {   276,  "default/ccir.020",                  "TR 2/1/.3" },
    {   277,  "default/ccir.021",                  "TR 1/2/.5" },
    {   278,  "default/ccir.022",                  "TR 1/2/.3" },
    {   279,  "default/ccir.023",                  "TR 1/1/.5" },
    {   280,  "default/ccir.024",                  "TR 1/1/.3" },
    {   281,  "default/ccir.025",                  "mni 4dB [HQ 1/.3]" },
    {   282,  "default/ccir.026",                  "SWWhip for REC533" },
    {   529,  "default/const17.voa",               "Const 17dB transmit antenna used by VOA" },
    {   768,  "default/swwhip.voa",                "SWWhip.VOA used by VOA for receive antenna" },
    {  1024,  "samples/sample.00",                 "ISOTROPE :Sample type 00 Constant gain isotrope" },
    {  1025,  "samples/sample.01",                 "HR 4/4/1 :Sample type 01 Multiband Aperiodic Reflector Array" },
    {  1026,  "samples/sample.02",                 "HR 2/2/.3 :Sample type 2 Dual-Band Center-Fed Half-Wave Dipole Array" },
    {  1027,  "samples/sample.03",                 "HR 4/4/.5 :Sample type 03 Dual-Band End-Fed Half-Wave Dipole Array" },
    {  1028,  "samples/sample.04",                 "TR 2/1/.5 :Sample type 04 Tropical Array" },
    {  1029,  "samples/sample.05",                 "LPH 29/.8/31.1/67.1/7/21.60/450 :Sample type 05 Horiz Log-Periodic" },
    {  1030,  "samples/sample.06",                 "LPV 12/4/25/56/2/14/450 :Sample type 06 Vertical Lop-Periodic" },
    {  1031,  "samples/sample.07",                 "RH155/40.3/68 :Sample type 07 Horizontal Rhombic" },
    {  1032,  "samples/sample.08",                 "Omni 4dB [HQ 1/.3] :Sample type 08 Quadrant Antenna" },
    {  1033,  "samples/sample.09",                 "HX .3 :Sample type 09 Crossed-Dipole Antenna" },
    {  1034,  "samples/sample.10",                 "VM 8/8/120/3 :Sample type 10 Vertical Monopole" },
    {  1035,  "samples/sample.11",                 "SWWhip for REC533 :Sample type 11 Gain Table versus Elevation Angle" },
    {  1036,  "samples/sample.12",                 "HR 4/4/1 :Sample type 12 Curtain Array NTIA Report 87-215" },
    {  1037,  "samples/sample.13",                 "HR 4/4/.5 :Sample type 13 360 degree gain table" },
    {  1039,  "samples/sample.14",                 "RH155/40.3/68 :Sample type 14 Point-to-Point gain @ 30 freqs" },
    {  1045,  "samples/sample.21",                 "RH67/88/17 :Sample type 21 ITSA-1 Terminated Horizontal Rhombic" },
    {  1046,  "samples/sample.22",                 "VM/.25 :Sample type 22 ITSA-1 Vertical Monopole" },
    {  1047,  "samples/sample.23",                 "HD/.5/.25 :Sample type 23 ITSA-1 Horizontal Dipole" },
    {  1048,  "samples/sample.24",                 "HY/.5/.25 :Sample type 24 ITSA-1 Horizontal Yagi" },
    {  1049,  "samples/sample.25",                 "VLP/.25/2 :Sample type 25 ITSA-1 Vertical Log-Periodic" },
    {  1050,  "samples/sample.26",                 "H/2/4 :Sample type 26 ITSA-1 Curtain" },
    {  1051,  "samples/sample.27",                 "V23/122/15/1.8 :Sample type 27 ITSA-1 Sloping Vee" },
    {  1052,  "samples/sample.28",                 "L/21/10 :Sample type 28 ITSA-1 Inverted L" },
    {  1053,  "samples/sample.29",                 "SR/23/88/17/8 :Sample type 29 ITSA-1 Sloping Rhombic" },
    {  1054,  "samples/sample.30",                 "IR/70/114/20/4 :Sample type 30 ITSA-1 Interlaced Rhombic" },
    {  1055,  "samples/sample.31",                 "RH67/88/17 :Sample type 31 ITS-78 Terminated Horizontal Rhombic" },
    {  1056,  "samples/sample.32",                 "VM/.25 :Sample type 32 ITS-78 Vertical Monopole" },
    {  1058,  "samples/sample.34",                 "HY/.5/.25 :Sample type 34 ITS-78 Horizontal Yagi" },
    {  1059,  "samples/sample.35",                 "VD/.5/.25 :Sample type 35 ITS-78 Vertical Dipole" },
    {  1060,  "samples/sample.36",                 "H/2/4 :Sample type 36 ITS-78 Curtain" },
    {  1061,  "samples/sample.37",                 "V23/122/15/1.8 :Sample type 37 ITS-78 Terminated Sloping Vee" },
    {  1062,  "samples/sample.38",                 "L/21/10 :Sample type 38 ITS-78 Inverted L" },
    {  1063,  "samples/sample.39",                 "SR/23/88/17/8 :Sample type 39 ITS-78 Terminated Sloping Rhombic" },
    {  1065,  "samples/sample.41",                 "SLW10/91/0 :Sample type 41 ITS-78 Sloping Long Wire" },
    {  1067,  "samples/sample.43",                 "HxD3/33/54/450 :Sample type 43 ITS-78 Horizontal X-Dipole Log Periodic" },
    {  1068,  "samples/sample.44",                 "ATD45/.5/.25 :Sample type 44 ITS-78 Arbitrary Tilted Dipole" },
    {  1069,  "samples/sample.45",                 "SLR28/80 :Sample type 45 ITS-78 Side-Loaded Vertical Half-Rhombic" },
    {  1070,  "samples/sample.46",                 "SDR62/150 :Sample type 46 ITS-78 Sloping Double-Rhomboid" },
    {  1071,  "samples/sample.47",                 "VM/.25/76/2/120 :Sample type 47 ITS-78 Vertical Monopole + Ground Screen" },
    {  1072,  "samples/sample.48",                 "INVCONE :Sample type 48 NOSC Inverted Cone antenna" },
    {  1114,  "samples/sample.90",                 "IONCAP Rhombic - External type 90 - Terminated Horizontal Rhombic, sample.21" },
    {  1123,  "samples/sample.99",                 "ISOTROPE :Sample type 99 Harris antenna" },
    {  1294,  "samples/sample.14x",                "RH155/40.3/68 :Sample type 14 Point-to-Point gain @ 30 freqs" },
};
// clang-format on

static const std::size_t ANTENNA_DATA_COUNT =
	sizeof(ANTENNA_DATA) / sizeof(ANTENNA_DATA[0]);

#endif // ANTENNA_DATA_H
