/*
 * HamClock antennas.html page, baked in as a C string.
 * Companion to liveweb.cpp — served on the R/W port as /antennas.html
 */
// LICENSE_BEGIN
// Copyright (c) 2026 David Strickland KR8X
// Contributor to HamClock by Elwood Charles Downey.
// SPDX-License-Identifier: MIT
// See LICENSE file distributed with HamClock for full license text.
// LICENSE_END

#include "HamClock.h"

const char antennas_html[] =
	"<!--\n"
	"  Copyright (c) 2026 David Strickland KR8X\n"
	"  Contributor to HamClock by Elwood Charles Downey.\n"
	"  SPDX-License-Identifier: MIT\n"
	"  See LICENSE file distributed with HamClock for full license text.\n"
	"-->\n"
	"<!DOCTYPE html>\n"
	"<html lang=\"en\">\n"
	"<head>\n"
	"<meta charset=\"UTF-8\">\n"
	"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
	"<title>HamClock Antenna Manager</title>\n"
	"<style>\n"
	"  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
	"\n"
	"  body {\n"
	"    font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif;\n"
	"    font-size: 14px;\n"
	"    background: #f5f5f5;\n"
	"    color: #1a1a1a;\n"
	"    padding: 1.5rem 1rem;\n"
	"  }\n"
	"\n"
	"  h1 {\n"
	"    font-size: 20px;\n"
	"    font-weight: 500;\n"
	"    margin-bottom: 0.25rem;\n"
	"  }\n"
	"\n"
	"  .subtitle {\n"
	"    font-size: 13px;\n"
	"    color: #666;\n"
	"    margin-bottom: 1.5rem;\n"
	"  }\n"
	"\n"
	"  .card {\n"
	"    background: #fff;\n"
	"    border: 1px solid #e0e0e0;\n"
	"    border-radius: 10px;\n"
	"    padding: 1rem 1.25rem;\n"
	"    margin-bottom: 1rem;\n"
	"    max-width: 680px;\n"
	"  }\n"
	"\n"
	"  .card-title {\n"
	"    font-size: 11px;\n"
	"    font-weight: 500;\n"
	"    color: #888;\n"
	"    text-transform: uppercase;\n"
	"    letter-spacing: 0.06em;\n"
	"    margin-bottom: 0.75rem;\n"
	"  }\n"
	"\n"
	"  .row {\n"
	"    display: flex;\n"
	"    gap: 10px;\n"
	"    align-items: flex-end;\n"
	"    flex-wrap: wrap;\n"
	"  }\n"
	"\n"
	"  .field {\n"
	"    flex: 1;\n"
	"    min-width: 140px;\n"
	"  }\n"
	"\n"
	"  .field label {\n"
	"    display: block;\n"
	"    font-size: 12px;\n"
	"    color: #666;\n"
	"    margin-bottom: 5px;\n"
	"  }\n"
	"\n"
	"  select, input[type=\"number\"] {\n"
	"    width: 100%;\n"
	"    padding: 7px 10px;\n"
	"    border: 1px solid #ccc;\n"
	"    border-radius: 6px;\n"
	"    font-size: 13px;\n"
	"    background: #fff;\n"
	"    color: #1a1a1a;\n"
	"  }\n"
	"\n"
	"  select:disabled, input:disabled {\n"
	"    background: #f5f5f5;\n"
	"    color: #aaa;\n"
	"  }\n"
	"\n"
	"  select:focus, input:focus {\n"
	"    outline: none;\n"
	"    border-color: #378add;\n"
	"    box-shadow: 0 0 0 2px rgba(55,138,221,0.15);\n"
	"  }\n"
	"\n"
	"  button {\n"
	"    padding: 7px 16px;\n"
	"    font-size: 13px;\n"
	"    border-radius: 6px;\n"
	"    cursor: pointer;\n"
	"    border: 1px solid #ccc;\n"
	"    background: transparent;\n"
	"    color: #1a1a1a;\n"
	"    white-space: nowrap;\n"
	"    transition: background 0.1s;\n"
	"  }\n"
	"\n"
	"  button:hover:not(:disabled) { background: #f0f0f0; }\n"
	"  button:active:not(:disabled) { transform: scale(0.98); }\n"
	"  button:disabled { opacity: 0.4; cursor: not-allowed; }\n"
	"\n"
	"  .btn-primary {\n"
	"    background: #e6f1fb;\n"
	"    color: #0c447c;\n"
	"    border-color: #85b7eb;\n"
	"  }\n"
	"\n"
	"  .btn-primary:hover:not(:disabled) { background: #cfe4f7; }\n"
	"\n"
	"  .status {\n"
	"    font-size: 12px;\n"
	"    padding: 7px 10px;\n"
	"    border-radius: 6px;\n"
	"    margin-top: 0.75rem;\n"
	"    display: none;\n"
	"  }\n"
	"\n"
	"  .status.ok  { display: block; background: #eaf3de; color: #27500a; }\n"
	"  .status.err { display: block; background: #fcebeb; color: #791f1f; }\n"
	"  .status.inf { display: block; background: #f0f0f0; color: #555; }\n"
	"\n"
	"  .badge {\n"
	"    display: none;\n"
	"    font-size: 11px;\n"
	"    padding: 2px 7px;\n"
	"    border-radius: 5px;\n"
	"    background: #eaf3de;\n"
	"    color: #27500a;\n"
	"    margin-left: 8px;\n"
	"    vertical-align: middle;\n"
	"  }\n"
	"\n"
	"  .meta {\n"
	"    font-size: 12px;\n"
	"    color: #999;\n"
	"    margin-top: 6px;\n"
	"  }\n"
	"\n"
	"  .ctrl-row {\n"
	"    display: flex;\n"
	"    gap: 10px;\n"
	"    align-items: center;\n"
	"    flex-wrap: wrap;\n"
	"  }\n"
	"\n"
	"  .ctrl-row label {\n"
	"    font-size: 12px;\n"
	"    color: #666;\n"
	"    min-width: 120px;\n"
	"  }\n"
	"</style>\n"
	"</head>\n"
	"<body>\n"
	"\n"
	"<h1>Antenna manager</h1>\n"
	"<p class=\"subtitle\">Controls HamClock antenna selection - DE, DX index and DE/DX control mode</p>\n"
	"\n"
	"<div id=\"st-load\" class=\"status\" style=\"max-width:680px; margin-bottom:1rem;\"></div>\n"
	"\n"
	"<div class=\"card\">\n"
	"  <div class=\"card-title\">DE/DX antenna control mode</div>\n"
	"  <div class=\"ctrl-row\">\n"
	"    <label>antdedxcontrol</label>\n"
	"    <select id=\"sel-control\" disabled style=\"width:220px\">\n"
	"      <option value=\"0\">0 - neither (manual)</option>\n"
	"      <option value=\"1\">1 - DE antenna active</option>\n"
	"      <option value=\"2\">2 - DX antenna active</option>\n"
	"      <option value=\"3\">3 - both active</option>\n"
	"    </select>\n"
	"    <button class=\"btn-primary\" id=\"btn-control\" onclick=\"setControl()\" disabled>Set</button>\n"
	"  </div>\n"
	"  <p class=\"meta\">Controls which antenna index is sent to the backend</p>\n"
	"  <div id=\"st-control\" class=\"status\"></div>\n"
	"</div>\n"
	"\n"
	"<div class=\"card\">\n"
	"  <div class=\"card-title\">\n"
	"    DE antenna\n"
	"    <span id=\"de-badge\" class=\"badge\"></span>\n"
	"  </div>\n"
	"  <div class=\"row\">\n"
	"    <div class=\"field\">\n"
	"      <label>Antenna (antdeindex)</label>\n"
	"      <select id=\"sel-de\" disabled>\n"
	"        <option>-- loading --</option>\n"
	"      </select>\n"
	"    </div>\n"
	"    <div class=\"field\" style=\"max-width:120px\">\n"
	"      <label>Az (antdeaz) deg</label>\n"
	"      <input type=\"number\" id=\"inp-de-az\" min=\"0\" max=\"360\" step=\"0.1\" disabled placeholder=\"0.0\">\n"
	"    </div>\n"
	"    <button class=\"btn-primary\" id=\"btn-de\" onclick=\"setDE()\" disabled>Set DE</button>\n"
	"  </div>\n"
	"  <div id=\"st-de\" class=\"status\"></div>\n"
	"</div>\n"
	"\n"
	"<div class=\"card\">\n"
	"  <div class=\"card-title\">\n"
	"    DX antenna\n"
	"    <span id=\"dx-badge\" class=\"badge\"></span>\n"
	"  </div>\n"
	"  <div class=\"row\">\n"
	"    <div class=\"field\">\n"
	"      <label>Antenna (antdxindex)</label>\n"
	"      <select id=\"sel-dx\" disabled>\n"
	"        <option>-- loading --</option>\n"
	"      </select>\n"
	"    </div>\n"
	"    <div class=\"field\" style=\"max-width:120px\">\n"
	"      <label>Az (antdxaz) deg</label>\n"
	"      <input type=\"number\" id=\"inp-dx-az\" min=\"0\" max=\"360\" step=\"0.1\" disabled placeholder=\"0.0\">\n"
	"    </div>\n"
	"    <button class=\"btn-primary\" id=\"btn-dx\" onclick=\"setDX()\" disabled>Set DX</button>\n"
	"  </div>\n"
	"  <div id=\"st-dx\" class=\"status\"></div>\n"
	"</div>\n"
	"\n"
	"<script>\n"
	"// Copyright (c) 2026 David Strickland KR8X\n"
	"// Contributor to HamClock by Elwood Charles Downey.\n"
	"// SPDX-License-Identifier: MIT\n"
	"// See LICENSE file distributed with HamClock for full license text.\n"
	"\n"
	"'use strict';\n"
	"\n"
	"// Each entry: { index: <numeric index from col1>, desc: <description from col3> }\n"
	"let antennaList = [];\n"
	"\n"
	"function setStatus(id, msg, type) {\n"
	"    const el = document.getElementById(id);\n"
	"    el.textContent = msg;\n"
	"    el.className = 'status ' + type;\n"
	"}\n"
	"\n"
	"function clearStatus(id) {\n"
	"    document.getElementById(id).className = 'status';\n"
	"}\n"
	"\n"
	"// All fetches use relative paths -- always same-origin as the page itself.\n"
	"async function getText(path) {\n"
	"    const r = await fetch(path);\n"
	"    if (!r.ok) throw new Error('HTTP ' + r.status);\n"
	"    return r.text();\n"
	"}\n"
	"\n"
	"/* Parse list_antennas.txt output.\n"
	" * Format (after header lines):\n"
	" *      0 isotrope     ISOTROPE\n"
	" *    256 ccir.000     ISOTROPE\n"
	" *    257 ccir.001     HR 4/4/1\n"
	" * Col 1 (fields[0]) = numeric index used in set_antennas\n"
	" * Col 2 (fields[1]) = model name (ignored)\n"
	" * Col 3+ (fields[2+]) = description (may contain spaces)\n"
	" * Skip the header line \"Index model Description\" and the \"list antennas:\" line.\n"
	" */\n"
	"function parseList(text) {\n"
	"    const result = [];\n"
	"    for (const line of text.split('\\n')) {\n"
	"        const trimmed = line.trim();\n"
	"        // skip blank lines, the \"list antennas:\" header, and the column heading line\n"
	"        if (!trimmed) continue;\n"
	"        if (trimmed.startsWith('list antennas')) continue;\n"
	"        if (trimmed.startsWith('Index')) continue;\n"
	"\n"
	"        // split on whitespace, max 3 parts: index, model, description(rest)\n"
	"        const parts = trimmed.split(/\\s+/);\n"
	"        if (parts.length < 3) continue;\n"
	"\n"
	"        const idx = parseInt(parts[0]);\n"
	"        if (isNaN(idx)) continue;\n"
	"\n"
	"        // description is everything from parts[2] onward\n"
	"        const desc = parts.slice(2).join(' ');\n"
	"\n"
	"        result.push({ index: idx, desc: desc });\n"
	"    }\n"
	"    return result;\n"
	"}\n"
	"\n"
	"function parseGetAntennas(text) {\n"
	"    const out = { deindex: null, dxindex: null, control: null, deaz: null, dxaz: null };\n"
	"    for (const line of text.split('\\n')) {\n"
	"        let m;\n"
	"        if ((m = line.match(/antdeindex\\s+set to\\s+(\\d+)/i)))   out.deindex = parseInt(m[1]);\n"
	"        if ((m = line.match(/antdxindex\\s+set to\\s+(\\d+)/i)))   out.dxindex = parseInt(m[1]);\n"
	"        if ((m = line.match(/antdedxcontrol:\\s*(\\d+)/i)))        out.control = parseInt(m[1]);\n"
	"        if ((m = line.match(/antdeaz\\s+set to\\s+([\\d.]+)/i)))    out.deaz    = parseFloat(m[1]);\n"
	"        if ((m = line.match(/antdxaz\\s+set to\\s+([\\d.]+)/i)))    out.dxaz    = parseFloat(m[1]);\n"
	"    }\n"
	"    return out;\n"
	"}\n"
	"\n"
	"/* Populate a select with antenna entries.\n"
	" * option value = the real numeric index (e.g. 256), not the array position.\n"
	" * option text  = \"256 - HR 4/4/1\"\n"
	" */\n"
	"function populateSel(id, list, currentIndex) {\n"
	"    const sel = document.getElementById(id);\n"
	"    sel.innerHTML = '';\n"
	"    for (const ant of list) {\n"
	"        const o = document.createElement('option');\n"
	"        o.value = ant.index;\n"
	"        o.textContent = ant.index + ' - ' + ant.desc;\n"
	"        if (ant.index === currentIndex) o.selected = true;\n"
	"        sel.appendChild(o);\n"
	"    }\n"
	"    sel.disabled = false;\n"
	"}\n"
	"\n"
	"function findDesc(index) {\n"
	"    const ant = antennaList.find(a => a.index === index);\n"
	"    return ant ? ant.desc : '';\n"
	"}\n"
	"\n"
	"function setBadge(id, index) {\n"
	"    const b = document.getElementById(id);\n"
	"    const desc = findDesc(index);\n"
	"    if (index !== null && desc) {\n"
	"        b.textContent = index + ' - ' + desc;\n"
	"        b.style.display = 'inline';\n"
	"    } else {\n"
	"        b.style.display = 'none';\n"
	"    }\n"
	"}\n"
	"\n"
	"async function loadAll() {\n"
	"    setStatus('st-load', 'Loading antenna data...', 'inf');\n"
	"    try {\n"
	"        const [listText, stateText] = await Promise.all([\n"
	"            getText('/list_antennas.txt'),\n"
	"            getText('/get_antennas.txt')\n"
	"        ]);\n"
	"\n"
	"        antennaList = parseList(listText);\n"
	"        if (antennaList.length === 0) {\n"
	"            setStatus('st-load', 'No antennas returned from list_antennas.txt', 'err');\n"
	"            return;\n"
	"        }\n"
	"\n"
	"        const state = parseGetAntennas(stateText);\n"
	"\n"
	"        populateSel('sel-de', antennaList, state.deindex);\n"
	"        populateSel('sel-dx', antennaList, state.dxindex);\n"
	"        setBadge('de-badge', state.deindex);\n"
	"        setBadge('dx-badge', state.dxindex);\n"
	"\n"
	"        if (state.control !== null)\n"
	"            document.getElementById('sel-control').value = state.control;\n"
	"        document.getElementById('sel-control').disabled = false;\n"
	"        document.getElementById('btn-control').disabled = false;\n"
	"\n"
	"        const deAz = document.getElementById('inp-de-az');\n"
	"        const dxAz = document.getElementById('inp-dx-az');\n"
	"        deAz.disabled = false;\n"
	"        dxAz.disabled = false;\n"
	"        if (state.deaz !== null) deAz.value = state.deaz.toFixed(1);\n"
	"        if (state.dxaz !== null) dxAz.value = state.dxaz.toFixed(1);\n"
	"\n"
	"        document.getElementById('btn-de').disabled = false;\n"
	"        document.getElementById('btn-dx').disabled = false;\n"
	"\n"
	"        setStatus('st-load',\n"
	"            antennaList.length + ' antennas loaded' +\n"
	"            (state.deindex !== null ? ' - DE: ' + state.deindex + ' (' + findDesc(state.deindex) + ')' : '') +\n"
	"            (state.dxindex !== null ? ', DX: ' + state.dxindex + ' (' + findDesc(state.dxindex) + ')' : '') +\n"
	"            (state.control !== null ? ', control: ' + state.control : ''), 'ok');\n"
	"\n"
	"    } catch (e) {\n"
	"        setStatus('st-load', 'Failed to load: ' + e.message, 'err');\n"
	"    }\n"
	"}\n"
	"\n"
	"async function setControl() {\n"
	"    const v = document.getElementById('sel-control').value;\n"
	"    clearStatus('st-control');\n"
	"    setStatus('st-control', 'Setting antdedxcontrol=' + v + '...', 'inf');\n"
	"    try {\n"
	"        await getText('/set_antennas?antdedxcontrol=' + v);\n"
	"        setStatus('st-control', 'antdedxcontrol set to ' + v, 'ok');\n"
	"    } catch (e) {\n"
	"        setStatus('st-control', 'Failed: ' + e.message, 'err');\n"
	"    }\n"
	"}\n"
	"\n"
	"async function setDE() {\n"
	"    // value is the real numeric index (e.g. 256), not array position\n"
	"    const idx = parseInt(document.getElementById('sel-de').value);\n"
	"    const az  = document.getElementById('inp-de-az').value;\n"
	"    clearStatus('st-de');\n"
	"    let params = 'antdeindex=' + idx;\n"
	"    if (az !== '') params += '&antdeaz=' + parseFloat(az).toFixed(1);\n"
	"    setStatus('st-de', 'Setting ' + params + '...', 'inf');\n"
	"    try {\n"
	"        await getText('/set_antennas?' + params);\n"
	"        setBadge('de-badge', idx);\n"
	"        setStatus('st-de', 'DE antenna set to index ' + idx + ' - ' + findDesc(idx), 'ok');\n"
	"    } catch (e) {\n"
	"        setStatus('st-de', 'Failed: ' + e.message, 'err');\n"
	"    }\n"
	"}\n"
	"\n"
	"async function setDX() {\n"
	"    // value is the real numeric index (e.g. 256), not array position\n"
	"    const idx = parseInt(document.getElementById('sel-dx').value);\n"
	"    const az  = document.getElementById('inp-dx-az').value;\n"
	"    clearStatus('st-dx');\n"
	"    let params = 'antdxindex=' + idx;\n"
	"    if (az !== '') params += '&antdxaz=' + parseFloat(az).toFixed(1);\n"
	"    setStatus('st-dx', 'Setting ' + params + '...', 'inf');\n"
	"    try {\n"
	"        await getText('/set_antennas?' + params);\n"
	"        setBadge('dx-badge', idx);\n"
	"        setStatus('st-dx', 'DX antenna set to index ' + idx + ' - ' + findDesc(idx), 'ok');\n"
	"    } catch (e) {\n"
	"        setStatus('st-dx', 'Failed: ' + e.message, 'err');\n"
	"    }\n"
	"}\n"
	"\n"
	"// Auto-load on page open.\n"
	"window.addEventListener('DOMContentLoaded', loadAll);\n"
	"</script>\n"
	"</body>\n"
	"</html>\n"
	;
